In [1]:
import numpy as np #np es un alias de numpy

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import sys

In [5]:
print("Hello Word")


Hello Word


In [5]:
lista1 = list(range(1,11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
promedio = np.mean(lista1)
promedio


np.float64(5.5)

**Cambiando lista a array**

In [7]:
arreglo = np.array(lista1)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
type(arreglo)

numpy.ndarray

**creando lista solo de unos**

In [13]:
unos = np.ones(100)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**consultando el tipo de dato**

In [14]:
type(lista1)

list

**consultando el tipo de dato numerico**

In [22]:
arreglo.dtype

dtype('int64')

**Lista de Datos Compuesto**

In [24]:
lista2 = list['Leonardo', 'viernes', 12, 9.5, True]
lista2

list['Leonardo', 'viernes', 12, 9.5, True]

In [10]:
arreglo1 = np.array(lista2) # cambiando lista 2 a array
arreglo1

array(list['Leonardo', 'viernes', 12, 9.5, True], dtype=object)

In [12]:
type(arreglo1)

numpy.ndarray

In [14]:
arreglo1.dtype

dtype('O')

In [26]:
lista3 = list[12,20,4,6,7,8,9]
lista3

list[12, 20, 4, 6, 7, 8, 9]

In [27]:
arreglo2 = np.array(lista3)
arreglo2

array(list[12, 20, 4, 6, 7, 8, 9], dtype=object)

In [28]:
type(arreglo2)

numpy.ndarray

**tranformando entero a float**

In [29]:
new_arreglo = arreglo.astype(np.float16)
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float16)

In [30]:
np.random.rand()  #genera numeros aleatorios de [0,1]

0.4773652731187531

In [31]:
np.random.rand(5) # genera n catidad de numeros

array([0.9904469 , 0.37806526, 0.25624145, 0.13554491, 0.65459781])

In [33]:
np.random.randint(1,100,15) # genera 10 numeros aleatorios del 1 al 100

array([26, 81, 21, 28, 14, 76, 15, 71, 15, 45, 88, 39, 17, 61, 81],
      dtype=int32)

In [35]:
arreglo4 = np.arange(1,11)
arreglo4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arreglo5 = np.random.randint(1,101,(5,10))
arreglo5

array([[91, 56,  7,  5, 83, 51, 79, 42, 97, 29],
       [83, 15,  1, 77, 37, 86, 65, 20, 25, 41],
       [54, 88, 55, 24,  2, 80, 13, 63, 14, 15],
       [27, 71, 58, 20, 47, 39, 78, 53,  1, 81],
       [18, 77, 65, 52, 41, 40, 81, 27, 70,  9]], dtype=int32)

In [38]:
arreglo6 = np.random.choice(1,10)
arreglo6

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [44]:
print(arreglo5.shape)

(5, 10)


In [45]:
print(arreglo6.reshape)

<built-in method reshape of numpy.ndarray object at 0x000002C2FB9660D0>
