In [8]:
import numpy as np #np es un alias de numpy

In [9]:
import pandas as pd

In [10]:
import matplotlib.pyplot as plt

In [1]:
import sys

In [2]:
print("Hello Word")


Hello Word


In [5]:
lista1 = list(range(1,11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
promedio = np.mean(lista1)
promedio


np.float64(5.5)

**Cambiando lista a array**

In [12]:
arreglo = np.array(lista1)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**creando lista solo de unos**

In [13]:
unos = np.ones(100)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**consultando el tipo de dato**

In [14]:
type(lista1)

list

**consultando el tipo de dato numerico**

In [15]:
arreglo.dtype

dtype('int64')

**Lista de Datos Compuesto**

In [25]:
lista2 = list['Leonardo', 'viernes', 12, 9.5, True]
lista2

list['Leonardo', 'viernes', 12, 9.5, True]

In [ ]:
arreglo1 = np.array(lista2) # camciando lista [] a array
arreglo1

array(list['Leo', 'viernes', 12, 9.5, True], dtype=object)

In [23]:
lista3 = list[12,20,4,6,7,8,9]
lista3

list[12, 20, 4, 6, 7, 8, 9]

In [24]:
arreglo2 = np.array(lista3)
arreglo2

array(list[12, 20, 4, 6, 7, 8, 9], dtype=object)

In [30]:
type(arreglo2)

numpy.ndarray

**tranformando entero a float**

In [33]:
new_arreglo = arreglo.astype(np.float16)
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float16)

In [ ]:
np.random.rand()  #genera numeros aleatorios de [0,1]

0.4162887778490222

In [ ]:
np.random.rand(5) # genera n catidad de numeros

array([0.66074125, 0.74166266, 0.65951211, 0.25221316, 0.30313737])

In [ ]:
np.random.randint(1,100,10) # genera 10 numeros aleatorios del 1 al 100

array([66, 18, 63, 20, 31,  7, 99, 68, 27, 81], dtype=int32)

In [47]:
arreglo4 = np.arange(1.11)
arreglo4

array([0., 1.])

In [50]:
arreglo5 = np.random.randint(1,101,(10,10))
arreglo5

array([[ 18,  24,  88,  33,  90,  21,  39, 100,   1,  22],
       [ 39,   8,   6,  34,  75,  23,  23,  89,  41,  66],
       [ 66,  37,  69,  56,  25,  41,  29,  36,  29,  98],
       [ 82,  14,  13,  10,  37,  70,  60,   6,  15,  64],
       [ 51,  26,  14,  29,  93,   8,  22,  42,  49,  52],
       [ 52,  46,  82,  77,  24,  62,  80,  41,  37,  82],
       [ 79,  41,  76,  64,  35,  50,  61,  42,   8,  60],
       [ 11,  62,  33,  72,  25,  15,   6,  37,  96,  56],
       [ 88,  20,  98,  70,  31,  98,  85,  79,  97,  54],
       [  8,  88,  30,  63,  14,  43,  70,  70,  64,  26]], dtype=int32)

In [58]:
arreglo6 = np.random.choice(1,10)
arreglo6

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)